{{-- resources/views/admin/reports/pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($request->report_type) }} Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #2563eb; }
        .report-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .summary { background-color: #f8f9fa; padding: 15px; margin: 20px 0; }
        .footer { text-align: center; margin-top: 30px; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">HARF Donation System</div>
        <h2>{{ ucfirst($request->report_type) }} Report</h2>
    </div>

    <div class="report-info">
        <strong>Report Generated:</strong> {{ $generated_at->format('F d, Y g:i A') }}<br>
        <strong>Date Range:</strong> {{ $request->date_from }} to {{ $request->date_to }}<br>
        @if($request->status)
            <strong>Status:</strong> {{ ucfirst($request->status) }}<br>
        @endif
        @if($request->donor_type)
            <strong>Donor Type:</strong> {{ ucfirst($request->donor_type) }}<br>
        @endif
    </div>

    @if($request->report_type === 'donations')
        <div class="summary">
            <strong>Summary:</strong><br>
            Total Donations: {{ $data->count() }}<br>
            Total Amount: ${{ number_format($data->sum('amount'), 2) }}<br>
            Average Donation: ${{ number_format($data->avg('amount'), 2) }}
        </div>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Donor</th>
                    <th>Amount</th>
                    <th>Payment Method</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $donation)
                    <tr>
                        <td>#{{ $donation->id }}</td>
                        <td>{{ $donation->is_anonymous ? 'Anonymous' : $donation->donor_name }}</td>
                        <td>${{ number_format($donation->amount, 2) }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', $donation->payment_method)) }}</td>
                        <td>{{ ucfirst($donation->status) }}</td>
                        <td>{{ $donation->created_at->format('M d, Y') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($request->report_type === 'donors')
        <div class="summary">
            <strong>Summary:</strong><br>
            Total Donors: {{ $data->count() }}<br>
            Monthly Donors: {{ $data->where('donor_type', 'monthly')->count() }}<br>
            One-time Donors: {{ $data->where('donor_type', 'one_time')->count() }}
        </div>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Joined Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $donor)
                    <tr>
                        <td>#{{ $donor->id }}</td>
                        <td>{{ $donor->name }}</td>
                        <td>{{ $donor->email }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', $donor->donor_type)) }}</td>
                        <td>{{ $donor->is_active ? 'Active' : 'Inactive' }}</td>
                        <td>{{ $donor->created_at->format('M d, Y') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by HARF Donation System Admin Panel<br>
        {{ $generated_at->format('F d, Y g:i A') }}
    </div>
</body>
</html>